### ISSUE TITLE
Could you share the schematics as PDF oder jpg? 😊

### ISSUE THREAD

**Issue by SkylightXD** [thorio/esphome-projects#1]
Could you share the schematics as PDF oder jpg? 😊
In this case for the doorbell

Thanks and regards
Christoph

**Comment by thorio** [comment]
I can:
![image](https://github.com/user-attachments/assets/0ed7a7fb-30f8-4dbf-b66f-cebdc1b1e39f)
![image](https://github.com/user-attachments/assets/59d07683-80cd-4548-85cd-fd1a6021d925)
![image](https://github.com/user-attachments/assets/a0a80545-6dfe-4b54-aa78-ba79d8dbdd04)
![image](https://github.com/user-attachments/assets/6c3fdd6d-1a0a-4095-a1e2-b894148e7985)
![image](https://github.com/user-attachments/assets/5064d4e3-db79-40b8-9576-03fe02c1b845)

**Comment by thorio** [comment]
However, I do not recommend building this with the ESP-01S, I've had a lot of connectivity issues.
The ESP-12F modules have yielded better results in my experience.

Note: The resistors on the buzzer size of the optocoupler should be chosen depending on the voltage of your buzzer. It should drop just enough voltage so the IR led in the optocoupler can run at a normal voltage. The trim pot is for adjusting sensitivity.

**Comment by SkylightXD** [comment]
Do you replace the buzzer with this PCB or make it parallel? Has the ESP-12F the same footprint?

**Comment by thorio** [comment]
I wired it in parallel to the existing buzzer.

The ESP-12F has a very different footprint and would require shuffling some components around on the board to fit.

**Comment by SkylightXD** [comment]
All right! Thanks a lot.

I think about a PCB for the Esp8266 Board, than it is more easy for me 😊
